# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('scheduler', models.CharField(choices=[('rightnow', 'ATONCE'), ('repeat', 'REPEAT'), ('reserved', 'RESERVED')], max_length=32)),
                ('emails', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TC_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('web', 'TC_WEB'), ('ios', 'TC_IOS'), ('android', 'TC_ANDROID'), ('es', 'TC_EMBEDDED'), ('vision', 'TC_VISION'), ('fc', 'TC_FC')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('cmd', models.CharField(max_length=32)),
                ('params', models.CharField(max_length=128)),
                ('script', models.CharField(max_length=256)),
                ('platform', models.CharField(choices=[('win', 'WIN'), ('mac', 'MAC'), ('linux', 'LNX')], max_length=32)),
                ('timeout', models.IntegerField(default=120)),
                ('ret_code', models.BooleanField(default=False)),
                ('error_msg', models.CharField(max_length=128)),
                ('log', models.CharField(max_length=128)),
            ],
        ),
    ]
