# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_suitemodel_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitemodel',
            name='cases',
            field=models.ManyToManyField(blank=True, null=True, to='automation.TC_Model'),
        ),
        migrations.AlterField(
            model_name='suitemodel',
            name='emails',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tc_model',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tc_model',
            name='error_msg',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tc_model',
            name='log',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tc_model',
            name='params',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
