# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20170722_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('web', 'TC_WEB'), ('ios', 'TC_IOS'), ('android', 'TC_ANDROID'), ('es', 'TC_EMBEDDED'), ('vision', 'TC_VISION'), ('fc', 'TC_FC')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('cmd', models.CharField(max_length=32)),
                ('params', models.CharField(blank=True, max_length=128, null=True)),
                ('script', models.CharField(max_length=256)),
                ('platform', models.CharField(choices=[('win', 'WIN'), ('mac', 'MAC'), ('linux', 'LNX')], max_length=32)),
                ('timeout', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='RunningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('ret_code', models.BooleanField(default=False)),
                ('error_msg', models.CharField(blank=True, max_length=128, null=True)),
                ('log', models.CharField(blank=True, max_length=128, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.CaseModel')),
            ],
        ),
        migrations.DeleteModel(
            name='TC_Model',
        ),
        migrations.AlterField(
            model_name='suitemodel',
            name='cases',
            field=models.ManyToManyField(blank=True, null=True, to='automation.CaseModel'),
        ),
    ]
