# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20170722_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRunningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('ret_code', models.BooleanField(default=False)),
                ('error_msg', models.CharField(blank=True, max_length=128, null=True)),
                ('log', models.CharField(blank=True, max_length=128, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.CaseModel')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRunningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ret', models.BooleanField(default=False)),
                ('error_msg', models.CharField(blank=True, max_length=256, null=True)),
                ('case_runnings', models.ManyToManyField(to='automation.CaseRunningModel')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.SuiteModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='runningmodel',
            name='case',
        ),
        migrations.DeleteModel(
            name='RunningModel',
        ),
    ]
