# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_auto_20170722_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitemodel',
            name='cases',
            field=models.ManyToManyField(to='automation.CaseModel'),
        ),
    ]
