# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_auto_20170722_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('Now', 'Run Now!'), ('Repeat', 'Every Day!'), ('Reserved', 'Reserved')], max_length=16)),
                ('emails', models.CharField(blank=True, max_length=256, null=True)),
                ('run_date', models.DateField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.SuiteModel')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerRunningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], max_length=16)),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.SchedulerModel')),
            ],
        ),
    ]
