# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_auto_20170727_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerrunningmodel',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
