# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20170727_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserunningmodel',
            name='schedule_running',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='automation.SchedulerRunningModel'),
        ),
        migrations.AddField(
            model_name='caserunningmodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
