# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 03:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_auto_20170801_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerrunningmodel',
            name='scheduler',
        ),
        migrations.RemoveField(
            model_name='caserunningmodel',
            name='schedule_running',
        ),
        migrations.RemoveField(
            model_name='caserunningmodel',
            name='task_id',
        ),
        migrations.AddField(
            model_name='suiterunningmodel',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='suiterunningmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], default='Pending', max_length=16),
        ),
        migrations.DeleteModel(
            name='SchedulerRunningModel',
        ),
    ]
