# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_suiterunningmodel_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suiterunningmodel',
            name='case_runnings',
        ),
        migrations.RemoveField(
            model_name='suiterunningmodel',
            name='schedule',
        ),
        migrations.AddField(
            model_name='caserunningmodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
