# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_auto_20170803_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserunningmodel',
            name='ret_code',
            field=models.IntegerField(default=1),
        ),
    ]
