# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 07:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_auto_20170805_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserunningmodel',
            name='run_time',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
