# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_suiterunningmodel_run_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulermodel',
            old_name='run_date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedulermodel',
            name='run_time',
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
