# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_auto_20170808_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2017, 8, 8, 7, 37, 28, 381247)),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 7, 37, 28, 381224), null=True),
        ),
    ]
