# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_auto_20170808_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_time',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 7, 59, 52, 906417), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_time',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 7, 59, 52, 906397), null=True),
        ),
    ]
