# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_auto_20170808_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulermodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedulermodel',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 10, 32, 673907), null=True),
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 10, 32, 673937), null=True),
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='repeat_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 10, 32, 673883), null=True),
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 10, 32, 673923), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='type',
            field=models.CharField(choices=[('ManualRun', 'Run Now!'), ('RepeatEveryDay', 'Every Day!'), ('RepeatWorkingDay', 'Every WorkingDay!'), ('Reserved', 'Reserved')], max_length=16),
        ),
    ]
