# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_auto_20170808_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 12, 25, 669659), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 12, 25, 669690), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='repeat_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 12, 25, 669635), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 8, 11, 12, 25, 669676), null=True),
        ),
    ]
