# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 03:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0028_auto_20170808_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCaseModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('web', 'TC_WEB'), ('ios', 'TC_IOS'), ('android', 'TC_ANDROID'), ('es', 'TC_EMBEDDED'), ('vision', 'TC_VISION'), ('fc', 'TC_FC')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('cmd', models.CharField(max_length=32)),
                ('params', models.CharField(blank=True, max_length=128, null=True)),
                ('script', models.CharField(max_length=256)),
                ('platform', models.CharField(choices=[('win', 'WIN'), ('mac', 'MAC'), ('linux', 'LNX')], max_length=32)),
                ('timeout', models.IntegerField(default=120)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical case model',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSchedulerModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(choices=[('ManualRun', 'Run Now!'), ('RepeatEveryDay', 'Every Day!'), ('RepeatWorkingDay', 'Every WorkingDay!'), ('Reserved', 'Reserved')], max_length=16)),
                ('emails', models.CharField(blank=True, max_length=256, null=True)),
                ('appoint_at', models.TimeField(blank=True, default=datetime.datetime(2017, 8, 10, 3, 11, 48, 403450), null=True)),
                ('start_day', models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 3, 11, 48, 403478), null=True)),
                ('end_day', models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 3, 11, 48, 403501), null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suite', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='automation.SuiteModel')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical scheduler model',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSuiteModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('emails', models.CharField(blank=True, max_length=256, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical suite model',
            },
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 10, 3, 11, 48, 403450), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 3, 11, 48, 403501), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 3, 11, 48, 403478), null=True),
        ),
    ]
