# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0031_auto_20170810_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsuitemodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='suitemodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
    ]
