# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0032_auto_20170810_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsuitemodel',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='suitemodel',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
