# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0036_auto_20170810_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalschedulermodel',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalschedulermodel',
            name='suite',
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 8, 9, 328985), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 8, 9, 329026), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 8, 9, 329006), null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSchedulerModel',
        ),
    ]
