# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0039_auto_20170810_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 24, 31, 950733), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 24, 31, 950691), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 24, 31, 950773), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 4, 24, 31, 950754), null=True),
        ),
    ]
