# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0042_auto_20170810_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 10, 6, 57, 49, 940048), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 10, 6, 57, 49, 940008), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 6, 57, 49, 940085), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 6, 57, 49, 940067), null=True),
        ),
    ]
