# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0043_auto_20170810_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulermodel',
            name='appoint_at',
            field=models.TimeField(blank=True, default=datetime.datetime(2017, 8, 10, 7, 21, 17, 738893), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 10, 7, 21, 17, 738849), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='end_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 7, 21, 17, 738933), null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 10, 7, 21, 17, 738914), null=True),
        ),
    ]
