# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0048_auto_20170810_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedulermodel',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='schedulermodel',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
