# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0049_auto_20170810_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requirement', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AddField(
            model_name='historicalschedulermodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedulermodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
